# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &defaults
  facebook:
    app_id: 842337999153841
    secret: 569134af954600ae1214cb8573ff3566
  api_location: http://localhost:4000

  yelp:
    consumer_key: qAl0zMCeUnc4c4OLBVyWNg
    consumer_secret: AJPudb8hgM1FuuXtFyNPifCjpUE
    token: lP5c-RUO2Axn-I2Uqrc19adLfU-uPwGW
    token_secret: mg8FJ4cMpCzurIRAZzjYhUwzfKk

development:
  secret_key_base: 7ef2a39ec204b6360a2eece0f0bb9acbd20f55a6b67145d9428f58cba5806963877b84d1de5be6b18b5bb1440f441fd6161e0707058d22cc0e969861bc594758
  <<: *defaults

test:
  secret_key_base: 9043c2a2a5a957a4926f57fb70c4d0670acb08f00b95ab045830ab803df0a9e5ec8b89a8d589222eba570b218c15b66f8b06fd2ad21d665e317d095fae38328d
  <<: *defaults

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *defaults
  api_location: https://next-api.hotmess.social
  facebook:
    app_id: 915436455177328
    secret: <%= ENV["FACEBOOK_SECRET"] %>


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *defaults
  api_location: https://api.hotmess.social
  facebook:
    app_id: 713525445368431
    secret: <%= ENV["FACEBOOK_SECRET"] %>
